version: '2.1'

services:

  ordering:
    build: ./orderingService
    ports:
      - "3001:3001"
    depends_on:
      mongo:
        condition: service_healthy
    volumes:
      - ./orderingService:/app
      - ./orderingService/node_modules:/app/node_modules
    command: sh ./entrypoint.sh
    environment:
      - API_PORT=3001

  shipment:
    build: ./shipmentService
    ports:
      - "3002:3002"
    depends_on:
      mongo:
        condition: service_healthy
    volumes:
      - ./shipmentService:/app
      - ./shipmentService/node_modules:/app/node_modules
    command: sh ./entrypoint.sh
    environment:
      - API_PORT=3002

  kafka:
    image: landoop/fast-data-dev
    ports:
      - "2181:2181" # ZK
      - "3030:3030" # UI
      - "8081:8081" 
      - "8082:8082"
      - "8083:8083"
      - "9092:9092" # Broker
    environment:
      ADV_HOST: 'kafka'

  mongo:
    image: mongo:latest
    ports:
      - "27017"
    command: mongod --smallfiles
    healthcheck:
      test: ["CMD-SHELL", "echo 'db.stats().ok' | mongo 192.168.5.51:30000/test --quiet"]
      interval: 5s
      retries: 10